import { Inter, Montserrat, Hind, Hind_Guntur, Roboto_Condensed, Arimo } from "next/font/google";
import "./globals.css";
import Header from "../components/header";
import { CartProvider } from "@/context/cart";
import { FiltersProvider } from "@/context/filters";
import Footer from "@/components/footer";
import { ResponsiveProvider } from "@/context/responsive";


const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({ subsets: ['latin'] })
const roboto = Roboto_Condensed({ subsets: ['latin'], weight: ['400'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <FiltersProvider>
      <ResponsiveProvider>
        <CartProvider>
          <html lang="en" className="">
            <body className={`${roboto.className} w-full flex justify-center items-center flex-col`}>
              <Header />
              {children}
              <Footer />
            </body>
          </html>
        </CartProvider>
      </ResponsiveProvider>


    </FiltersProvider>

  );
}
