import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "../components/header";
import { CartProvider } from "@/context/cart";
import { FiltersProvider } from "@/context/filters";
import NavBar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({subsets:['latin']})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <FiltersProvider>
      <html lang="en" className="">
        <body className={`${montserrat.className} w-full flex justify-center items-center flex-col`}>
          <Header />
          <NavBar/>
          {children}
        </body>
      </html>
    </FiltersProvider>

  );
}
